return {
	-- "olimorris/codecompanion.nvim",
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"nvim-treesitter/nvim-treesitter",
	-- },
	-- config = function()
	-- 	require("codecompanion").setup({
	-- 		adapters = {
	-- 			http = {
	-- 				anthropic = function()
	-- 					return require("codecompanion.adapters").extend("anthropic", {
	-- 						env = {
	-- 							api_key = "MY_OTHER_ANTHROPIC_KEY",
	-- 						},
	-- 					})
	-- 				end,
	-- 			},
	-- 		},
	-- 		strategies = {
	-- 			chat = {
	-- 				adapter = "copilot",
	-- 			},
	-- 			inline = {
	-- 				adapter = "copilot",
	-- 			},
	-- 		},
	-- 	})
	-- end,
}
