return {
	-- {
	-- 	"ellisonleao/gruvbox.nvim",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("gruvbox").setup({
	-- 			undercurl = true,
	-- 			underline = true,
	-- 			bold = true,
	-- 			italic = {
	-- 				emphasis = true,
	-- 				strings = true,
	-- 				comments = true,
	-- 				operators = false,
	-- 				folds = true,
	-- 			},
	-- 			strikethrough = true,
	-- 		})
	--
	-- 		vim.cmd("colorscheme gruvbox")
	-- 	end,
	-- },

	-- {
	-- 	"marko-cerovac/material.nvim",
	-- 	config = function()
	-- 		vim.cmd("colorscheme material")
	-- 		vim.g.material_style = "oceanic"
	-- 		vim.cmd("hi NonText guifg=bg")
	-- 		vim.api.nvim_set_hl(0, "TabLineEdge", { fg = "#2E3440" })
	-- 		vim.api.nvim_set_hl(0, "TabLineSelEdge", { fg = "#2E3440", bg = "#10AF98" })
	-- 		vim.api.nvim_set_hl(0, "SnacksPickerDir", { fg = "#4C5669" })
	-- 		vim.api.nvim_set_hl(0, "SnacksPickerPathHidden", { fg = "#4C5669" })
	-- 	end,
	-- },

	-- {
	-- 	"AlexvZyl/nordic.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("nordic").load()
	-- 		vim.api.nvim_set_hl(0, "Comment", { fg = "#4C5669", italic = true })
	-- 		vim.api.nvim_set_hl(0, "Visual", { bg = "#62573F" })
	-- 		vim.api.nvim_set_hl(0, "Winbar", { bg = "#303340" })
	-- 		vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#000000", bg = "#94BFCE" })
	-- 		-- vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#000000", bg = "#D79784" })
	-- 	end,
	-- },
	-- Pretty and readable but fairly Cattpuccinish
	-- {
	-- 	"fynnfluegge/monet.nvim",
	-- 	name = "monet",
	-- 	config = function()
	-- 		vim.cmd.colorscheme("monet")
	-- 	end,
	-- },
	-- {
	-- 	"everviolet/nvim",
	-- 	name = "evergarden",
	-- 	priority = 1000, -- Colorscheme plugin is loaded first before any other plugins
	-- 	opts = {
	-- 		theme = {
	-- 			variant = "spring", -- 'winter'|'fall'|'spring'|'summer'
	-- 			accent = "green",
	-- 		},
	-- 		editor = {
	-- 			transparent_background = false,
	-- 			sign = { color = "none" },
	-- 			float = {
	-- 				color = "mantle",
	-- 				invert_border = false,
	-- 			},
	-- 			completion = {
	-- 				color = "surface0",
	-- 			},
	-- 		},
	-- 	},
	-- 	config = function()
	-- 		vim.cmd.colorscheme("evergarden")
	-- 	end,
	-- },
	-- {
	-- 	"nyngwang/nvimgelion",
	-- 	config = function()
	-- 		-- do whatever you want for further customization~
	-- 		vim.cmd([[colorscheme nvimgelion]])
	-- 	end,
	-- },
	-- {
	-- 	"ramojus/mellifluous.nvim",
	-- 	-- version = "v0.*", -- uncomment for stable config (some features might be missed if/when v1 comes out)
	-- 	config = function()
	-- 		require("mellifluous").setup({}) -- optional, see configuration section.
	-- 		vim.cmd("colorscheme mellifluous")
	-- 	end,
	-- },
	-- {
	-- 	"fenetikm/falcon",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd.colorscheme("falcon")
	-- 		vim.api.nvim_set_hl(0, "Visual", { bg = "#4f4f59" })
	-- 		vim.api.nvim_set_hl(0, "CursorLine", { bg = "#4f4f59" })
	-- 		-- vim.api.nvim_set_hl(0, "Search", { bg = "#635196" })
	-- 		-- vim.api.nvim_set_hl(0, "CurSearch", { bg = "#bfdaff" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#b24d36" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignError", { fg = "#b24d36" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#ff3600" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#ff761a" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignWarn", { fg = "#ff761a" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarning", { fg = "#ff761a" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#99a4bc" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignInfo", { fg = "#99a4bc" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#99a4bc" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#99a4bc" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignHint", { fg = "#99a4bc" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#99a4bc" })
	-- 		vim.api.nvim_set_hl(0, "Winbar", { bg = "#303340" })
	-- 		vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#000000", bg = "#FFC552" })
	-- 		vim.api.nvim_set_hl(0, "SnacksPickerDir", { fg = "#FFC552" })
	-- 	end,
	-- },
	-- {
	-- 	"zortax/three-firewatch",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd("colorscheme three-firewatch")
	-- 		vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#D95360" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignError", { fg = "#D95360" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#D95360" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#D55118" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignWarn", { fg = "#D55118" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarning", { fg = "#D55118" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#DFB563" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignInfo", { fg = "#DFB563" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#DFB563" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#44A8B6" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignHint", { fg = "#44A8B6" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#44A8B6" })
	-- 		vim.api.nvim_set_hl(0, "Comment", { fg = "#4C5669", italic = true })
	-- 	end,
	-- },

	-- Best working Solarized theme
	-- {
	-- 	"svrana/neosolarized.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#B84745" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignError", { fg = "#B84745" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#B84745" })
	-- 		vim.api.nvim_set_hl(0, "SnacksPickerDir", { fg = "#4C5669" })
	-- 		vim.api.nvim_set_hl(0, "SnacksPickerPathHidden", { fg = "#4C5669" })
	--
	-- 		require("neosolarized").setup({
	-- 			comment_italics = true,
	-- 			background_set = true,
	-- 		})
	-- 		vim.cmd.colorscheme("neosolarized")
	-- 		vim.cmd("hi NonText guifg=bg")
	-- 		vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#B84745" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticSignError", { fg = "#B84745" })
	-- 		vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#B84745" })
	-- 		vim.api.nvim_set_hl(0, "SnacksPickerDir", { fg = "#4C5669" })
	-- 		vim.api.nvim_set_hl(0, "SnacksPickerPathHidden", { fg = "#4C5669" })
	-- 		vim.api.nvim_set_hl(0, "Winbar", { bg = "#002B35" })
	-- 	end,
	-- 	dependencies = {
	-- 		"tjdevries/colorbuddy.nvim",
	-- 	},
	-- },

	-- Real Solarized theme
	-- {
	-- 	"maxmx03/solarized.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	---@type solarized.config
	-- 	opts = {
	-- 		variant = "spring", -- "spring" | "summer" | "autumn" | "winter" (default)
	-- 	},
	-- 	config = function(_, opts)
	-- 		vim.o.termguicolors = true
	-- 		vim.o.background = "dark"
	-- 		require("solarized").setup(opts)
	-- 		vim.cmd.colorscheme("solarized")
	-- 	end,
	-- },
	{
		"ishan9299/nvim-solarized-lua",
		lazy = false,
		priority = 1000,
		config = function()
			vim.o.termguicolors = true
			vim.o.background = "dark"
			vim.cmd.colorscheme("solarized-flat")
			vim.api.nvim_set_hl(0, "CmpDocumentation", { bg = "#001D26" })
			vim.api.nvim_set_hl(0, "SnacksPicker", { bg = "none", nocombine = true })
			vim.g.solarized_italics = 1
			vim.g.solarized_visibility = "normal"
		end,
	},
	-- {
	-- 	"antonio-hickey/citrus-mist",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd("colorscheme citrus-mist")
	-- 	end,
	-- },
	-- {
	-- 	"folke/tokyonight.nvim",
	-- 	priority = 1000, -- make sure to load this before all the other start plugins
	-- 	config = function()
	-- 		-- load the colorscheme here
	-- 		vim.cmd([[colorscheme tokyonight-storm]])
	-- 	end,
	-- },
	-- {
	-- 	"sainnhe/everforest",
	-- 	priority = 1000, -- make sure to load this before all the other start plugins
	-- 	config = function()
	-- 		vim.cmd([[colorscheme everforest]])
	-- 	end,
	-- },
	-- {
	-- 	"sainnhe/gruvbox-material",
	-- 	priority = 1000, -- make sure to load this before all the other start plugins
	-- 	config = function()
	-- 		vim.cmd([[let g:gruvbox_material_background = 'soft']])
	-- 		vim.cmd([[let g:gruvbox_material_better_performance = 1]])
	-- 		vim.cmd([[let g:gruvbox_material_enable_bold = 1]])
	-- 		vim.cmd([[let g:gruvbox_material_enable_italic = 1]])
	-- 		vim.cmd([[]])
	-- 		vim.cmd([[colorscheme gruvbox-material]])
	-- 	end,
	-- },
	-- {
	-- 	"olivercederborg/poimandres.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("poimandres").setup({
	-- 			dim_nc_background = true,
	-- 			disable_italics = false,
	-- 		})
	-- 	end,
	--
	-- 	-- optionally set the colorscheme within lazy config
	-- 	init = function()
	-- 		vim.cmd("colorscheme poimandres")
	-- 		vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#a6998f" })
	-- 		vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#a6998f", bg = "#282828" })
	-- 		vim.api.nvim_set_hl(0, "Comment", { fg = "#a6998f", italic = true })
	-- 		vim.api.nvim_set_hl(0, "Winbar", { bg = "#303340" })
	-- 	end,
	-- },
	-- {
	-- 	"kyazdani42/blue-moon",
	-- 	config = function()
	-- 		vim.opt.termguicolors = true
	-- 		vim.cmd("colorscheme blue-moon")
	-- 	end,
	-- },
	-- {
	-- 	"rose-pine/neovim",
	-- 	name = "rose-pine",
	-- 	config = function()
	-- 		require("rose-pine").setup({
	-- 			dark_variant = "moon", -- main, moon, or dawn
	-- 			dim_inactive_windows = false,
	-- 			extend_background_behind_borders = true,
	-- 		})
	-- 		vim.opt.termguicolors = true
	-- 		vim.cmd("colorscheme rose-pine")
	-- 		vim.cmd("hi CursorLine guibg=#394549")
	-- 		vim.cmd("hi TabLineSel guibg=#394549")
	-- 		vim.cmd("hi Visual guifg=Black guibg=#F6C177 gui=none")
	-- 	end,
	-- },
}
