return {
	-- {
	-- 	"svrana/neosolarized.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("neosolarized").setup({
	-- 			comment_italics = true,
	-- 			background_set = false,
	-- 		})
	-- 		vim.cmd.colorscheme("neosolarized")
	-- 	end,
	-- 	dependencies = {
	-- 		"tjdevries/colorbuddy.nvim",
	-- 	},
	-- },
	-- { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
	-- {
	-- 	"Love-Pengy/lillilac.nvim",
	-- 	priority = 1000, -- make sure to load this before all the other start plugins
	-- 	config = function()
	-- 		-- load the colorscheme here
	-- 		vim.cmd([[colorscheme lillilac]])
	-- 	end,
	-- },
	-- {
	-- 	"gbprod/nord.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("nord").setup({})
	-- 		vim.cmd.colorscheme("nord")
	-- 	end,
	-- },
	{
		"AlexvZyl/nordic.nvim",
		lazy = false,
		priority = 1000,
		config = function()
			require("nordic").load()
			vim.api.nvim_set_hl(0, "Comment", { fg = "#4C5669", italic = true })
			vim.api.nvim_set_hl(0, "Visual", { bg = "#62573F" })
			vim.api.nvim_set_hl(0, "Winbar", { bg = "#303340" })
			vim.api.nvim_set_hl(0, "TabLineSel", { bg = "#62573F" })
		end,
	},
	-- {
	-- 	"diegoulloao/neofusion.nvim",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.o.background = "dark"
	-- 		vim.cmd([[ colorscheme neofusion ]])
	-- 	end,
	-- 	opts = {},
	-- },
	-- {
	-- 	"0xstepit/flow.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	opts = {},
	-- 	config = function()
	-- 		require("flow").setup({
	-- 			dark_theme = true, -- Set the theme with dark background.
	-- 			high_contrast = false, -- Make the dark background darker or the light background lighter.
	-- 			transparent = false, -- Set transparent background.
	-- 			fluo_color = "pink", -- Color used as fluo. Available values are pink, yellow, orange, or green.
	-- 			mode = "base", -- Mode of the colors. Available values are: dark, bright, desaturate, or base.
	-- 			aggressive_spell = false, -- Use colors for spell check.
	-- 		})
	--
	-- 		vim.cmd("colorscheme flow")
	-- 	end,
	-- },
	-- {
	-- 	"nyngwang/nvimgelion",
	-- 	config = function()
	-- 		-- do whatever you want for further customization~
	-- 		vim.cmd([[colorscheme nvimgelion]])
	-- 	end,
	-- },
	-- {
	-- 	"luisiacc/gruvbox-baby",
	-- 	priority = 1000, -- make sure to load this before all the other start plugins
	-- 	config = function()
	-- 		-- load the colorscheme here
	-- 		vim.cmd([[colorscheme gruvbox-baby]])
	-- 	end,
	-- },
	-- {
	-- 	"lmburns/kimbox",
	-- 	config = function()
	-- 		require("kimbox").setup({
	-- 			-- options
	-- 		})
	-- 		require("kimbox").load()
	-- 		-- or
	-- 		vim.cmd("colorscheme kimbox")
	-- 	end,
	-- },
	-- {
	-- 	"ramojus/mellifluous.nvim",
	-- 	-- version = "v0.*", -- uncomment for stable config (some features might be missed if/when v1 comes out)
	-- 	config = function()
	-- 		require("mellifluous").setup({}) -- optional, see configuration section.
	-- 		vim.cmd("colorscheme mellifluous")
	-- 	end,
	-- },
	-- {
	-- 	"Mofiqul/adwaita.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- },
	-- {
	-- 	"lalitmee/cobalt2.nvim",
	-- 	event = { "ColorSchemePre" }, -- if you want to lazy load
	-- 	dependencies = { "tjdevries/colorbuddy.nvim", tag = "v1.0.0" },
	-- 	init = function()
	-- 		require("colorbuddy").colorscheme("cobalt2")
	-- 	end,
	-- },
	-- {
	-- 	"okaihe/okai",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("okai").setup({})
	-- 		vim.cmd([[colorscheme okai]])
	-- 	end,
	-- },
	-- {
	-- 	"fenetikm/falcon",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		-- require("falcon").load()
	-- 		-- vim.api.nvim_set_hl(0, "Comment", { fg = "#4C5669", italic = true })
	-- 		-- vim.api.nvim_set_hl(0, "Visual", { bg = "#62573F" })
	-- 		-- vim.api.nvim_set_hl(0, "Winbar", { bg = "#303340" })
	-- 		-- vim.api.nvim_set_hl(0, "TabLineSel", { bg = "#62573F" })
	-- 		vim.cmd.colorscheme("falcon")
	-- 	end,
	-- },
	-- {
	-- 	"kvrohit/rasmus.nvim",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd([[colorscheme rasmus]])
	-- 	end,
	-- },
	-- {
	-- 	"alligator/accent.vim",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd([[colorscheme accent]])
	-- 	end,
	-- },
	-- {
	-- 	"vague2k/vague.nvim",
	-- 	config = function()
	-- 		require("vague").setup({
	-- 			-- optional configuration here
	-- 		})
	-- 	end,
	-- },
	-- {
	-- 	"zortax/three-firewatch",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd("colorscheme three-firewatch")
	-- 	end,
	-- },
	-- {
	-- 	"antonio-hickey/citrus-mist",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd("colorscheme citrus-mist")
	-- 	end,
	-- },
	-- {
	-- 	"Biscuit-Theme/nvim",
	-- 	as = "biscuit",
	-- 	config = function()
	-- 		vim.cmd("colorscheme biscuit")
	-- 	end,
	-- },
	-- {
	-- 	"jalzn/altbox.nvim",
	-- 	config = function()
	-- 		require("altbox").setup()
	-- 	end,
	-- },
	-- vim.cmd([[colorscheme lucius]]),
	-- {
	-- 	"bluz71/vim-nightfly-guicolors",
	-- 	priority = 1000, -- make sure to load this before all the other start plugins
	-- 	config = function()
	-- 		-- load the colorscheme here
	-- 		vim.cmd([[colorscheme nightfly]])
	-- 	end,
	-- },
	-- {
	-- 	"folke/tokyonight.nvim",
	-- 	priority = 1000, -- make sure to load this before all the other start plugins
	-- 	config = function()
	-- 		local bg = "#011628"
	-- 		local bg_dark = "#011423"
	-- 		local bg_highlight = "#143652"
	-- 		local bg_search = "#0A64AC"
	-- 		local bg_visual = "#275378"
	-- 		local fg = "#CBE0F0"
	-- 		local fg_dark = "#B4D0E9"
	-- 		local fg_gutter = "#627E97"
	-- 		local border = "#547998"
	--
	-- 		require("tokyonight").setup({
	-- 			style = "night",
	-- 			on_colors = function(colors)
	-- 				colors.bg = bg
	-- 				colors.bg_dark = bg_dark
	-- 				colors.bg_float = bg_dark
	-- 				colors.bg_highlight = bg_highlight
	-- 				colors.bg_popup = bg_dark
	-- 				colors.bg_search = bg_search
	-- 				colors.bg_statusline = bg_dark
	-- 				colors.bg_sidebar = bg_dark
	-- 				colors.bg_visual = bg_visual
	-- 				colors.border = border
	-- 				colors.fg = fg
	-- 				colors.fg_dark = fg_dark
	-- 				colors.fg_float = fg
	-- 				colors.fg_gutter = fg_gutter
	-- 				colors.fg_sidebar = fg_dark
	-- 			end,
	-- 		})
	-- 		-- load the colorscheme here
	-- 		vim.cmd([[colorscheme tokyonight]])
	-- 		vim.cmd([[highlight Normal ctermbg=NONE guibg=NONE]])
	-- 	end,
	-- },
	-- {
	-- 	"sainnhe/everforest",
	-- 	priority = 1000, -- make sure to load this before all the other start plugins
	-- 	config = function()
	-- 		vim.cmd([[colorscheme everforest]])
	-- 	end,
	-- },
	-- {
	-- 	"sainnhe/gruvbox-material",
	-- 	priority = 1000, -- make sure to load this before all the other start plugins
	-- 	config = function()
	-- 		vim.cmd([[let g:gruvbox_material_background = 'soft']])
	-- 		vim.cmd([[let g:gruvbox_material_better_performance = 1]])
	-- 		vim.cmd([[let g:gruvbox_material_enable_bold = 1]])
	-- 		vim.cmd([[let g:gruvbox_material_enable_italic = 1]])
	-- 		vim.cmd([[]])
	-- 		vim.cmd([[colorscheme gruvbox-material]])
	-- 	end,
	-- },
	-- {
	-- 	"savq/melange-nvim",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd([[colorscheme melange]])
	-- 	end,
	-- },
	-- {
	-- 	"lvim-tech/lvim-colorscheme",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		local lvim_colorscheme = require("lvim-colorscheme")
	--
	-- 		lvim_colorscheme.setup({
	-- 			style = "dark",
	-- 		})
	-- 	end,
	-- },
	-- {
	-- 	"olivercederborg/poimandres.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("poimandres").setup({
	-- 			dim_nc_background = true,
	-- 			disable_italics = false,
	-- 		})
	-- 	end,
	--
	-- 	-- optionally set the colorscheme within lazy config
	-- 	init = function()
	-- 		vim.cmd("colorscheme poimandres")
	-- 		vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#a6998f" })
	-- 		vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#a6998f", bg = "#282828" })
	-- 		vim.api.nvim_set_hl(0, "Comment", { fg = "#a6998f", italic = true })
	-- 		vim.api.nvim_set_hl(0, "Winbar", { bg = "#303340" })
	-- 	end,
	-- },
	-- {
	-- 	"kyazdani42/blue-moon",
	-- 	config = function()
	-- 		vim.opt.termguicolors = true
	-- 		vim.cmd("colorscheme blue-moon")
	-- 	end,
	-- },
	-- {
	-- 	"lourenci/github-colors",
	-- 	config = function()
	-- 		vim.opt.termguicolors = true
	-- 		vim.cmd("colorscheme github-colors")
	-- 	end,
	-- },
	-- {
	-- 	"rose-pine/neovim",
	-- 	name = "rose-pine",
	-- 	config = function()
	-- 		require("rose-pine").setup({
	-- 			dark_variant = "moon", -- main, moon, or dawn
	-- 			dim_inactive_windows = false,
	-- 			extend_background_behind_borders = true,
	-- 		})
	-- 		vim.opt.termguicolors = true
	-- 		vim.cmd("colorscheme rose-pine")
	-- 		vim.cmd("hi CursorLine guibg=#394549")
	-- 		vim.cmd("hi TabLineSel guibg=#394549")
	-- 		vim.cmd("hi Visual guifg=Black guibg=#F6C177 gui=none")
	-- 	end,
	-- },
	-- {
	-- 	"catppuccin/nvim",
	-- 	name = "catppuccin",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("catppuccin").setup({
	-- 			flavour = "auto", -- latte, frappe, macchiato, mocha
	-- 			transparent_background = true,
	-- 			dim_inactive = {
	-- 				enabled = true, -- dims the background color of inactive window
	-- 				shade = "dark",
	-- 				percentage = 0.15, -- percentage of the shade to apply to the inactive window
	-- 			},
	-- 			default_integrations = true,
	-- 			integrations = {
	-- 				cmp = true,
	-- 				gitsigns = true,
	-- 				nvimtree = true,
	-- 				treesitter = true,
	-- 				notify = false,
	-- 				-- For more plugins integrations please scroll down (https://github.com/catppuccin/nvim#integrations)
	-- 			},
	-- 		})
	--
	-- 		vim.cmd.colorscheme("catppuccin")
	-- 	end,
	-- },
}
