---@module "lazy"
---@type LazySpec
return {
	"nvim-treesitter/nvim-treesitter",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-context",
	},
	branch = "main",
	lazy = false,
	build = ":TSUpdate",
	config = function()
		local treesitter = require("nvim-treesitter")
		treesitter.install({
			"bash",
			"comment",
			"css",
			"diff",
			"dockerfile",
			"fish",
			"git_config",
			"git_rebase",
			"gitcommit",
			"gitignore",
			"html",
			"javascript",
			"json",
			"latex",
			"lua",
			"luadoc",
			"make",
			"markdown",
			"markdown_inline",
			"norg",
			"python",
			"query",
			"regex",
			"scss",
			"svelte",
			"toml",
			"tsx",
			"typescript",
			"typst",
			"vim",
			"vimdoc",
			"vue",
			"xml",
			"yaml",
		})
	end,
}
