vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "reham_mist"
vim.o.termguicolors = true

-- reham_mist: a quiet, high-contrast monochrome palette.
-- Built to match the desktop language (niri/quickshell/kitty):
-- pure black background, near-white foreground, cool grey ramps.
-- A single soft accent keeps syntax scannable without breaking the calm.

local C = {
  ink        = "#0a0a0a",
  bg         = "#0f0f0f",
  bg_soft    = "#141414",
  bg_mid     = "#1b1b1b",
  bg_raised  = "#222222",
  border     = "#2c2c2c",
  border_hi  = "#3a3a3a",
  grey       = "#808080",
  grey_soft  = "#999999",
  fg_soft    = "#b3b3b3",
  fg         = "#e9e9e9",
  bright     = "#ffffff",
  accent     = "#d4b88c",
  accent_hi  = "#e8d6b0",
  dim        = "#4d4d4d",
  error      = "#e08a8a",
  warn       = "#d9c08a",
  info       = "#9fb6cc",
  ok         = "#a8c4a0",
}

local palette = {
  black   = C.bg,
  red     = C.error,
  green   = C.ok,
  yellow  = C.warn,
  blue    = C.info,
  magenta = C.accent,
  cyan    = C.info,
  white   = C.fg,
  grey    = C.grey,
}

for i, c in ipairs({ "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white", "grey" }) do
  vim.g["terminal_color_" .. (i - 1)] = palette[c]
end

local function hl(name, v)
  vim.api.nvim_set_hl(0, name, v)
end

-- Core
hl("Normal", { fg = C.fg, bg = C.bg })
hl("NormalNC", { fg = C.fg_soft, bg = C.bg })
hl("NormalFloat", { fg = C.fg, bg = C.bg_raised })
hl("FloatBorder", { fg = C.border_hi, bg = C.bg_raised })
hl("FloatTitle", { fg = C.accent, bg = C.bg_soft, bold = true })
hl("Cursor", { fg = C.bg, bg = C.bright })
hl("CursorLine", { bg = C.bg_soft })
hl("CursorColumn", { bg = C.bg_soft })
hl("ColorColumn", { bg = C.bg_soft })
hl("LineNr", { fg = C.dim })
hl("CursorLineNr", { fg = C.bright, bold = true })
hl("SignColumn", { bg = C.bg })
hl("FoldColumn", { fg = C.grey, bg = C.bg })
hl("VertSplit", { fg = C.border, bg = C.bg })
hl("WinSeparator", { fg = C.border, bg = C.bg })
hl("WinBar", { fg = C.fg_soft, bg = C.bg_soft, bold = true })
hl("WinBarNC", { fg = C.grey, bg = C.bg })
hl("Visual", { bg = C.bg_raised })
hl("VisualNOS", { bg = C.bg_mid })
hl("Search", { fg = C.bg, bg = C.accent, bold = true })
hl("IncSearch", { fg = C.bg, bg = C.accent_hi, bold = true })
hl("CurSearch", { fg = C.bg, bg = C.bright, bold = true })
hl("Substitute", { fg = C.bg, bg = C.accent })
hl("Question", { fg = C.bright, bold = true })
hl("QuickFixLine", { bg = C.bg_mid, bold = true })
hl("StatusLine", { fg = C.bright, bg = C.bg_raised })
hl("StatusLineNC", { fg = C.grey, bg = C.bg })
hl("TabLine", { fg = C.grey, bg = C.bg })
hl("TabLineFill", { bg = C.bg })
hl("TabLineSel", { fg = C.bg, bg = C.bright, bold = true })
hl("Title", { fg = C.accent, bold = true })
hl("Directory", { fg = C.info })
hl("EndOfBuffer", { fg = C.bg })
hl("Conceal", { fg = C.grey })
hl("NonText", { fg = C.dim })
hl("SpecialKey", { fg = C.grey })
hl("Whitespace", { fg = C.dim })
hl("Pmenu", { fg = C.fg, bg = C.bg_raised })
hl("PmenuSel", { fg = C.bg, bg = C.accent, bold = true })
hl("PmenuSbar", { bg = C.bg_mid })
hl("PmenuThumb", { bg = C.grey })
hl("PmenuKind", { fg = C.info, bg = C.bg_raised })
hl("PmenuKindSel", { fg = C.bg, bg = C.accent, bold = true })
hl("PmenuExtra", { fg = C.grey_soft, bg = C.bg_raised })
hl("PmenuExtraSel", { fg = C.bg, bg = C.accent })
hl("WildMenu", { fg = C.bg, bg = C.accent, bold = true })
hl("MatchParen", { fg = C.accent_hi, bold = true, underline = true })
hl("Folded", { fg = C.grey_soft, bg = C.bg_soft, italic = true })
hl("ModeMsg", { fg = C.fg_soft, bold = true })
hl("MoreMsg", { fg = C.info, bold = true })
hl("WarningMsg", { fg = C.warn, bold = true })
hl("ErrorMsg", { fg = C.error, bold = true })
hl("MsgArea", { fg = C.fg, bg = C.bg })
hl("MsgSeparator", { fg = C.border, bg = C.bg })
hl("SpellBad", { undercurl = true, sp = C.error })
hl("SpellCap", { undercurl = true, sp = C.warn })
hl("SpellLocal", { undercurl = true, sp = C.info })
hl("SpellRare", { undercurl = true, sp = C.accent })
hl("DiffAdd", { fg = C.bg, bg = C.ok })
hl("DiffChange", { fg = C.bg, bg = C.warn })
hl("DiffDelete", { fg = C.bg, bg = C.error })
hl("DiffText", { fg = C.bg, bg = C.accent, bold = true })

-- Syntax
hl("Comment", { fg = C.grey, italic = true })
hl("Constant", { fg = C.accent })
hl("String", { fg = C.accent_hi })
hl("Character", { fg = C.ok })
hl("Number", { fg = C.accent })
hl("Boolean", { fg = C.accent, bold = true })
hl("Float", { fg = C.accent })
hl("Identifier", { fg = C.fg })
hl("Function", { fg = C.info })
hl("Statement", { fg = C.bright })
hl("Conditional", { fg = C.bright, italic = true })
hl("Repeat", { fg = C.bright, italic = true })
hl("Label", { fg = C.bright })
hl("Operator", { fg = C.info })
hl("Keyword", { fg = C.bright, bold = true })
hl("Exception", { fg = C.error, bold = true })
hl("PreProc", { fg = C.fg_soft })
hl("Include", { fg = C.bright })
hl("Define", { fg = C.bright })
hl("Macro", { fg = C.accent })
hl("PreCondit", { fg = C.bright })
hl("Type", { fg = C.fg_soft })
hl("StorageClass", { fg = C.bright })
hl("Structure", { fg = C.fg_soft })
hl("Typedef", { fg = C.fg_soft })
hl("Special", { fg = C.accent })
hl("SpecialChar", { fg = C.ok })
hl("Tag", { fg = C.bright })
hl("Delimiter", { fg = C.fg_soft })
hl("SpecialComment", { fg = C.info, italic = true })
hl("Debug", { fg = C.error })
hl("Underlined", { underline = true })
hl("Ignore", { fg = C.dim })
hl("Error", { fg = C.error, bold = true })
hl("Todo", { fg = C.bg, bg = C.warn, bold = true })

-- Treesitter
hl("@variable", { fg = C.fg })
hl("@variable.builtin", { fg = C.error })
hl("@variable.parameter", { fg = C.fg_soft })
hl("@constant", { fg = C.accent })
hl("@constant.builtin", { fg = C.accent, bold = true })
hl("@module", { fg = C.fg_soft })
hl("@label", { fg = C.bright })
hl("@function", { fg = C.info })
hl("@function.builtin", { fg = C.info })
hl("@function.call", { fg = C.info })
hl("@function.macro", { fg = C.accent })
hl("@constructor", { fg = C.fg_soft })
hl("@parameter", { fg = C.fg_soft })
hl("@keyword", { fg = C.bright, bold = true })
hl("@keyword.function", { fg = C.bright, bold = true })
hl("@keyword.operator", { fg = C.bright })
hl("@keyword.return", { fg = C.bright, italic = true })
hl("@keyword.conditional", { fg = C.bright, italic = true })
hl("@keyword.repeat", { fg = C.bright, italic = true })
hl("@keyword.exception", { fg = C.error, bold = true })
hl("@keyword.storage", { fg = C.bright })
hl("@string", { fg = C.accent_hi })
hl("@string.documentation", { fg = C.ok, italic = true })
hl("@string.regexp", { fg = C.ok })
hl("@string.escape", { fg = C.ok })
hl("@string.special", { fg = C.ok })
hl("@string.special.url", { fg = C.info, underline = true })
hl("@character", { fg = C.ok })
hl("@type", { fg = C.fg_soft })
hl("@type.builtin", { fg = C.fg_soft, italic = true })
hl("@type.definition", { fg = C.fg_soft })
hl("@type.qualifier", { fg = C.bright })
hl("@attribute", { fg = C.accent })
hl("@property", { fg = C.info })
hl("@field", { fg = C.info })
hl("@operator", { fg = C.info })
hl("@punctuation.delimiter", { fg = C.fg_soft })
hl("@punctuation.bracket", { fg = C.fg_soft })
hl("@punctuation.special", { fg = C.info })
hl("@comment", { fg = C.grey, italic = true })
hl("@comment.documentation", { fg = C.grey_soft, italic = true })
hl("@comment.error", { fg = C.error })
hl("@comment.warning", { fg = C.warn })
hl("@comment.todo", { fg = C.bg, bg = C.warn, bold = true })
hl("@tag", { fg = C.bright })
hl("@tag.attribute", { fg = C.info })
hl("@tag.delimiter", { fg = C.fg_soft })
hl("@markup.heading", { fg = C.accent, bold = true })
hl("@markup.heading.1", { fg = C.accent, bold = true })
hl("@markup.heading.2", { fg = C.info, bold = true })
hl("@markup.heading.3", { fg = C.info })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.link", { fg = C.info, underline = true })
hl("@markup.raw", { fg = C.ok })
hl("@number", { fg = C.accent })
hl("@boolean", { fg = C.accent, bold = true })

-- LSP & diagnostics
hl("LspReferenceText", { bg = C.bg_mid })
hl("LspReferenceRead", { bg = C.bg_mid })
hl("LspReferenceWrite", { bg = C.bg_mid, underline = true })
hl("LspSignatureActiveParameter", { fg = C.accent_hi, bold = true })
hl("LspCodeLens", { fg = C.grey, italic = true })
hl("LspInlayHint", { fg = C.grey, bg = C.bg_soft, italic = true })
hl("DiagnosticError", { fg = C.error })
hl("DiagnosticWarn", { fg = C.warn })
hl("DiagnosticInfo", { fg = C.info })
hl("DiagnosticHint", { fg = C.grey_soft })
hl("DiagnosticOk", { fg = C.ok })
hl("DiagnosticUnderlineError", { undercurl = true, sp = C.error })
hl("DiagnosticUnderlineWarn", { undercurl = true, sp = C.warn })
hl("DiagnosticSignError", { fg = C.error, bg = C.bg })
hl("DiagnosticSignWarn", { fg = C.warn, bg = C.bg })
hl("DiagnosticSignInfo", { fg = C.info, bg = C.bg })
hl("DiagnosticSignHint", { fg = C.grey_soft, bg = C.bg })

-- Lazy / Mason / Telescope / WhichKey / treesitter heavy UIs
hl("LazyNormal", { fg = C.fg, bg = C.bg_raised })
hl("LazyH1", { fg = C.bg, bg = C.accent, bold = true })
hl("LazyH2", { fg = C.accent, bold = true })
hl("LazyButtonActive", { fg = C.bg, bg = C.accent, bold = true })
hl("LazyCommit", { fg = C.ok })
hl("LazyCommitType", { fg = C.bright })
hl("LazyReasonKeys", { fg = C.info })
hl("LazyValue", { fg = C.info })
hl("MasonNormal", { fg = C.fg, bg = C.bg_raised })
hl("MasonHeader", { fg = C.bg, bg = C.accent, bold = true })
hl("MasonHighlight", { fg = C.bright })
hl("MasonHighlightSecondary", { fg = C.info })
hl("TelescopeNormal", { fg = C.fg, bg = C.bg_raised })
hl("TelescopeBorder", { fg = C.border, bg = C.bg_raised })
hl("TelescopeTitle", { fg = C.bg, bg = C.accent, bold = true })
hl("TelescopePromptNormal", { fg = C.fg, bg = C.bg_mid })
hl("TelescopePromptTitle", { fg = C.bg, bg = C.accent, bold = true })
hl("TelescopePreviewTitle", { fg = C.bg, bg = C.ok, bold = true })
hl("TelescopeResultsTitle", { fg = C.bg, bg = C.info, bold = true })
hl("TelescopeSelection", { fg = C.bright, bg = C.bg_mid, bold = true })
hl("TelescopeSelectionCaret", { fg = C.accent, bg = C.bg_mid })
hl("TelescopeMatching", { fg = C.accent_hi, bold = true })
hl("NeoTreeNormal", { fg = C.fg_soft, bg = C.bg })
hl("NeoTreeNormalNC", { fg = C.grey, bg = C.bg })
hl("NeoTreeRootName", { fg = C.accent, bold = true })
hl("NeoTreeDirectoryName", { fg = C.info })
hl("NeoTreeFileName", { fg = C.fg_soft })
hl("NeoTreeFileIcon", { fg = C.grey_soft })
hl("NeoTreeGitAdded", { fg = C.ok })
hl("NeoTreeGitDeleted", { fg = C.error })
hl("NeoTreeGitModified", { fg = C.warn })
hl("NeoTreeGitUntracked", { fg = C.info })
hl("NvimTreeNormal", { link = "NeoTreeNormal" })
hl("NvimTreeFolderName", { link = "NeoTreeDirectoryName" })
hl("NvimTreeRootFolder", { link = "NeoTreeRootName" })
hl("GitSignsAdd", { fg = C.ok, bg = C.bg })
hl("GitSignsChange", { fg = C.warn, bg = C.bg })
hl("GitSignsDelete", { fg = C.error, bg = C.bg })
hl("WhichKey", { fg = C.info, bold = true })
hl("WhichKeyGroup", { fg = C.bright })
hl("WhichKeyDesc", { fg = C.fg })
hl("WhichKeyFloat", { bg = C.bg_raised })
hl("WhichKeyBorder", { fg = C.accent, bg = C.bg_raised })
hl("IblIndent", { fg = C.dim, nocombine = true })
hl("IblScope", { fg = C.grey, nocombine = true })
hl("DashboardHeader", { fg = C.accent, bold = true })
hl("DashboardCenter", { fg = C.info })
hl("DashboardShortCut", { fg = C.bright })
hl("DashboardFooter", { fg = C.grey, italic = true })
hl("NoicePopup", { fg = C.fg, bg = C.bg_raised })
hl("NoicePopupBorder", { fg = C.accent, bg = C.bg_raised })
hl("NoiceCmdline", { fg = C.fg, bg = C.bg_mid })
hl("NoiceCmdlinePopup", { fg = C.fg, bg = C.bg_mid })
hl("NoiceCmdlinePopupBorder", { fg = C.accent, bg = C.bg_mid })
hl("NoiceFormatProgressDone", { fg = C.bg, bg = C.ok })
hl("NoiceFormatProgressTodo", { fg = C.grey, bg = C.bg_mid })
hl("CmpNormal", { fg = C.fg, bg = C.bg_raised })
hl("CmpBorder", { fg = C.border, bg = C.bg_raised })
hl("CmpItemAbbr", { fg = C.fg })
hl("CmpItemAbbrMatch", { fg = C.accent_hi, bold = true })
hl("CmpItemMenu", { fg = C.grey, italic = true })
hl("CmpItemKind", { fg = C.info })
hl("CmpItemKindText", { fg = C.fg })
hl("CmpItemKindMethod", { fg = C.info })
hl("CmpItemKindFunction", { fg = C.info })
hl("CmpItemKindConstructor", { fg = C.fg_soft })
hl("CmpItemKindVariable", { fg = C.fg })
hl("CmpItemKindClass", { fg = C.fg_soft })
hl("CmpItemKindKeyword", { fg = C.bright })
hl("TroubleNormal", { fg = C.fg, bg = C.bg_raised })
hl("TroubleText", { fg = C.fg })
hl("TroubleCount", { fg = C.accent, bold = true })
hl("TodoBgFIX", { fg = C.bg, bg = C.error, bold = true })
hl("TodoBgHACK", { fg = C.bg, bg = C.warn, bold = true })
hl("TodoBgNOTE", { fg = C.bg, bg = C.info, bold = true })
hl("TodoBgTODO", { fg = C.bg, bg = C.ok, bold = true })
hl("LeapMatch", { fg = C.accent_hi, bold = true, underline = true })
hl("LeapLabel", { fg = C.bg, bg = C.accent_hi, bold = true })
hl("LeapBackdrop", { fg = C.dim })
hl("FlashBackdrop", { fg = C.dim })
hl("FlashLabel", { fg = C.bg, bg = C.accent, bold = true })
hl("FlashMatch", { fg = C.info, bold = true })
hl("MiniCursorword", { underline = true })
hl("MiniCursorwordCurrent", { underline = true })
hl("MiniIndentscopeSymbol", { fg = C.accent })
hl("MiniIndentscopePrefix", { nocombine = true })
hl("MiniJump", { fg = C.bg, bg = C.accent, bold = true })
hl("MiniStatuslineFilename", { fg = C.fg, bg = C.bg_raised })
hl("MiniStatuslineInactive", { fg = C.grey, bg = C.bg })
hl("MiniStatuslineModeCommand", { fg = C.bg, bg = C.warn, bold = true })
hl("MiniStatuslineModeInsert", { fg = C.bg, bg = C.info, bold = true })
hl("MiniStatuslineModeNormal", { fg = C.bg, bg = C.accent, bold = true })
hl("MiniStatuslineModeReplace", { fg = C.bg, bg = C.error, bold = true })
hl("MiniStatuslineModeVisual", { fg = C.bg, bg = C.ok, bold = true })
hl("MiniSurround", { fg = C.bg, bg = C.accent })
hl("MiniTablineCurrent", { fg = C.bright, bg = C.bg_raised, bold = true })
hl("MiniTablineFill", { bg = C.bg })
hl("MiniTablineHidden", { fg = C.grey, bg = C.bg })
hl("MiniTestFail", { fg = C.error, bold = true })
hl("MiniTestPass", { fg = C.ok, bold = true })
hl("NavicText", { fg = C.fg })
hl("NavicSeparator", { fg = C.grey })
hl("DapBreakpoint", { fg = C.error })
hl("DapStopped", { fg = C.ok })
hl("DapUIValue", { fg = C.fg })
hl("DapUIModifiedValue", { fg = C.accent, bold = true })
hl("DapUIFrameName", { fg = C.fg })
hl("NeotestAdapterName", { fg = C.accent, bold = true })
hl("NeotestFailed", { fg = C.error })
hl("NeotestPassed", { fg = C.ok })
hl("NeotestRunning", { fg = C.warn })
hl("NeotestSkipped", { fg = C.info })
hl("NeotestTest", { fg = C.fg })
hl("NeogitBranch", { fg = C.accent })
hl("NeogitRemote", { fg = C.accent })
hl("NeogitHunkHeaderHighlight", { fg = C.info, bg = C.bg_raised })
hl("NeogitNotificationInfo", { fg = C.info })
hl("NeogitNotificationWarning", { fg = C.warn })
hl("NeogitNotificationError", { fg = C.error })
hl("NeogitChangeModified", { fg = C.warn })
hl("NeogitChangeAdded", { fg = C.ok })
hl("NeogitChangeDeleted", { fg = C.error })
hl("FocusedSymbol", { bg = C.bg_mid })
hl("LightBulbSign", { fg = C.warn })
hl("OverseerRUNNING", { fg = C.info })
hl("OverseerSUCCESS", { fg = C.ok })
hl("OverseerFAILURE", { fg = C.error })
hl("HarpoonBorder", { fg = C.accent, bg = C.bg_raised })
hl("HarpoonWindow", { bg = C.bg_raised })
hl("FidgetTitle", { fg = C.accent, bold = true })
hl("FidgetTask", { fg = C.grey })
hl("barbecue_separator", { fg = C.grey })
hl("barbecue_dirname", { fg = C.grey })
hl("barbecue_basename", { fg = C.fg, bold = true })
hl("barbecue_context", { fg = C.fg })
hl("barbecue_context_file", { fg = C.info })
hl("RainbowDelimiterRed", { fg = C.error })
hl("RainbowDelimiterYellow", { fg = C.warn })
hl("RainbowDelimiterBlue", { fg = C.info })
hl("RainbowDelimiterGreen", { fg = C.ok })
hl("RainbowDelimiterViolet", { fg = C.bright })
hl("RainbowDelimiterCyan", { fg = C.info })
hl("YankyPut", { link = "IncSearch" })
hl("YankyYanked", { link = "IncSearch" })
hl("Hlargs", { fg = C.fg_soft })
